- $id: env
  type: object
  properties: {}
  required: []

- $id: config
  type: object
  properties:
    build:
      type: object
      properties: {}

      required: []

    config:
      type: object
      properties:
        title: { type: string }
        titleIcon: { type: string }

        apiUrl: { type: string, format: uri-reference }

        signupEnabled: { type: boolean }

        locales: { type: array, items: { type: string } }

        pushNotifications:
          type: object
          properties:
            guestEnabled: { type: boolean }
            userEnabled: { type: boolean }

          additionalProperties: false
          required: [guestEnabled, userEnabled]

      required: [title, signupEnabled]

  required: [build, config]
