- $id: env
  type: object
  properties: {}
  required: []

- $id: build
  type: object
  properties: {}
  required: []

- $id: config
  config:
      type: object
      properties: {}
      required: []
