name: build-resources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # every first day of month at 00:00

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerocluster/node
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt update
          apt install -y git
          cd build
          npm i --ignore-scripts
          npm run build
        shell: bash
